### ISSUE TITLE
Export Table Data with Dropped Requests

### ISSUE THREAD

**Issue by DanKub** [simioni87/auth_analyzer#24]
If you try to export table data which contains at least one dropped request, it ends with an error and HTML/XML file is not created. 

![2022-01-13_17-05-37](https://user-images.githubusercontent.com/16067388/149365997-c826f725-0380-4e02-9272-1d13db5e6914.png)

Export as HTML - Stacktrace:
```
java.lang.NullPointerException: Response cannot be null
	at burp.bp.analyzeResponse(Unknown Source)
	at burp.cyn.analyzeResponse(Unknown Source)
	at com.protect7.authanalyzer.util.DataExporter.createHTML(DataExporter.java:136)
	at com.protect7.authanalyzer.gui.dialog.DataExportDialog.<init>(DataExportDialog.java:113)
	at com.protect7.authanalyzer.gui.main.CenterPanel$1.run(CenterPanel.java:132)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
Export as XML - Stacktrace:
```
java.lang.NullPointerException: Response cannot be null
	at burp.bp.analyzeResponse(Unknown Source)
	at burp.cyn.analyzeResponse(Unknown Source)
	at com.protect7.authanalyzer.util.DataExporter.createXML(DataExporter.java:46)
	at com.protect7.authanalyzer.gui.dialog.DataExportDialog.<init>(DataExportDialog.java:117)
	at com.protect7.authanalyzer.gui.main.CenterPanel$1.run(CenterPanel.java:132)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
The issue is caused by an attempt to process empty response (as the original request has been dropped).
Could you fix that please?

Thank you,
Daniel

**Comment by simioni87** [comment]
Thanks for your report DanKub, I'll fix it with the next release.

**Comment by simioni87** [comment]
Hi @DanKub 
Fixed with the latest release. Thanks for your report.
